version: "3"
services:
  homework:
    build: ./hw
    volumes:
      - ./working_copy:/data
    working_dir: /data
    networks:
      - no-network

networks:
  no-network:
    driver: bridge
    internal: true
